name: Deploy Website

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to public repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          external_repository: averylAL/averylAL.github.io
          publish_branch: main   # GitHub Pages 会用 main
          publish_dir: ./ 